REM the usual suspects
start "Chrome" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe"
REM start "Cmder" "C:\cmder\Cmder.exe"
REM start "Discord" "C:\Users\dan\AppData\Local\Discord\Update.exe"
start "Outlook" "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"
REM start "Slack" "C:\Users\dan\AppData\Local\slack\slack.exe"
start "StreetSmart Edge" "C:\Program Files (x86)\Schwab\StreetSmart Edge\1.72.21.0\SSEdge.exe"
REM start "TradingView" "C:\Program Files\WindowsApps\TradingView.Desktop_1.0.0.1104_x64__r4b1km8ya33za\TradingView.exe"
REM start "WhatsApp" "C:\Users\dan\AppData\Local\WhatsApp\WhatsApp.exe"
REM start "Chia" "C:\Users\dan\AppData\Local\chia-blockchain\Chia.exe"
start "tastyworks" "C:\Program Files\tastyworks\tastyworks.exe"
start "thinkorswim" "C:\Program Files\thinkorswim\thinkorswim.exe"
start "Evernote" "C:\Users\dan\AppData\Local\Programs\Evernote\Evernote.exe"
