REM the usual suspects
REM start "Chrome" "C:\Program Files\Google\Chrome\Application\chrome.exe"
start "Comet" "C:\Users\dan\AppData\Local\Perplexity\Comet\Application\comet.exe"
REM start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe"
REM start "Cmder" "C:\cmder\Cmder.exe"
REM start "Discord" "C:\Users\dan\AppData\Local\Discord\Update.exe"
start "Outlook" "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"
REM start "1Password" "C:\Users\dan\AppData\Local\1Password\app\8\1Password.exe"
start "Claude" "C:\Users\dan\AppData\Local\AnthropicClaude\claude.exe"
REM start "Slack" "C:\Users\dan\AppData\Local\slack\slack.exe"
REM start "TradingView" "C:\Program Files\WindowsApps\TradingView.Desktop_1.0.0.1104_x64__r4b1km8ya33za\TradingView.exe"
REM start "WhatsApp" "C:\Users\dan\AppData\Local\WhatsApp\WhatsApp.exe"
start "TradeStation" "C:\Program Files (x86)\TradeStation 10.0\Program\ORPlat.exe"
start "tastytrade" "C:\Program Files\tastytrade\tastytrade.exe"
start "thinkorswim" "C:\Program Files\thinkorswim\thinkorswim.exe"
REM start "Evernote" "C:\Users\dan\AppData\Local\Programs\Evernote\Evernote.exe"
start "Obsidian" "C:\Program Files\Obsidian\Obsidian.exe"
